# sphinx autodoc complains if PAMlib doesn't exist when the docs are built,
# so wrap a try block around the import so we can still get autogenerated
# source docs
try:
    import PAMlib
except ImportError:
    PAMlib = None
