# sphinx autodoc complains if PUBSlib doesn't exist when the docs are built,
# so wrap a try block around the import so we can still get autogenerated
# source docs
try:
    import PUBSlib
except ImportError:
    PUBSlib = None
